---
- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade dist
  apt:
    upgrade: dist
  become: yes
  notify: reboot system

- name: Install git
  apt:
    name: ['git-all', 'tmux']
    state: latest
  become: yes

- name: "Copy .bash_profile"
  copy: src=.bash_profile dest=~/.bash_profile

- name: "Copy .tmux"
  copy: src=.tmux.conf dest=~/.tmux.conf
