---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install git
  apt:
    name: ['git-all', 'tmux']
    state: latest
  become: yes

- name: "Copy .bash_profile"
  copy: src=.bash_profile dest=~/.bash_profile
